[build]
  publish = "_site"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-netlify-cms"

[template.environment]
  NODE_VERSION = "18"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
