name: Daily Blog Post

on:
  schedule:
    # 毎日午前9時（UTC 0:00）に実行
    - cron: '0 0 * * *'
  workflow_dispatch:  # 手動実行用

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: cd blog-generator && npm install
        
      - name: Generate blog post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: cd blog-generator && node generate.js
        
      - name: Commit and push if changes
        run: |
          git config --global user.name 'Blog Bot'
          git config --global user.email 'bot@studioq.co.jp'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Add daily blog post $(date +'%Y-%m-%d')"
          git push
